# Generated by Django 3.0.4 on 2020-03-24 16:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_name', models.CharField(max_length=255)),
                ('x_axis_name', models.CharField(max_length=255)),
                ('axis_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend', to='trend_app.Description')),
            ],
        ),
    ]
