# Generated by Django 3.0.4 on 2020-03-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='axis_name',
            new_name='y_axis_name',
        ),
    ]
